# Generated by Django 5.0.2 on 2026-05-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('liked_profiles', models.ManyToManyField(related_name='blog_profile_liked', to='blog_profile_app.profile')),
                ('profile_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_profile', to='blog_profile_app.profile')),
            ],
        ),
    ]
