# Generated by Django 5.0.2 on 2026-05-11 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0001_initial'),
        ('blog_profile_app', '0002_remove_profile_is_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
