# Generated by Django 5.0.2 on 2026-05-23 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post_app", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="post_commented",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_post",
                to="blog_post_app.post",
            ),
        ),
    ]
