# Generated by Django 5.0.2 on 2026-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post_app", "0004_comment_post_commented"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status_post",
            field=models.CharField(
                choices=[("draft", "draft"), ("posted", "posted")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
