# Generated by Django 5.0.2 on 2026-05-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_post_app", "0005_post_status_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="profile_commented",
            new_name="profile_related",
        ),
    ]
