# Generated by Django 5.0.2 on 2026-05-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_instructor',
        ),
    ]
